name: Symfony

on:
  push:
    branches: [ "feature/ci"]
  pull_request:
    branches: [ "feature/ci" ]

permissions:
  contents: read

jobs:
  symfony-tests:
    runs-on: ubuntu-latest

    env:
      DATABASE_URL: "sqlite:///${{ github.workspace }}/var/app.db"
      APP_ENV: test

    steps:
      - uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          extensions: mbstring, xml, ctype, iconv, intl, sqlite3
          coverage: none

      - name: Cache Composer packages
        uses: actions/cache@v3
        with:
          path: vendor
          key: ${{ runner.os }}-php-${{ hashFiles('**/composer.lock') }}
          restore-keys: |
            ${{ runner.os }}-php-

      - name: Install Dependencies
        run: composer install --no-ansi --no-interaction --no-progress --prefer-dist

      - name: Clear cache
        run: php bin/console cache:clear --env=test

      - name: Create Database and Schema
        run: |
          mkdir -p var
          php bin/console doctrine:database:create
          php bin/console doctrine:schema:create
          php bin/console doctrine:fixtures:load --no-interaction

      - name: Load Fixtures
        run: php bin/console doctrine:fixtures:load --no-interaction --env=test

      - name: Debug routes
        run: php bin/console debug:router --env=test

      - name: Execute tests
        run: vendor/bin/phpunit
