name: Symfony

on:
  push:
    branches: [ "feature/ci" ]
  pull_request:
    branches: [ "feature/ci" ]

permissions:
  contents: read

jobs:
  symfony-tests:
    runs-on: ubuntu-latest

    env:
      APP_ENV: test
      APP_SECRET: ci-secret
      DATABASE_URL: "sqlite:///%kernel.project_dir%/var/app.db"

    steps:
      - uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          extensions: mbstring, xml, ctype, iconv, intl, sqlite3
          coverage: none

      - name: Install Dependencies
        run: composer install --no-ansi --no-interaction --no-progress --prefer-dist

      - name: Prepare Database
        run: |
          mkdir -p var
          rm -f var/app.db
          php bin/console doctrine:schema:create --env=test
          php bin/console doctrine:fixtures:load --no-interaction --env=test

      - name: Execute tests
        run: php bin/phpunit
